env:
    ORG: "devonfw"
    REPO_SOURCE: "getting-started"
    REPO_DEST: "getting-started.wiki"
    REPO_CONSOLIDATE: "devonfw-guide"
    GH_REPO_SOURCE: "github.com/${ORG}/${REPO_SOURCE}.git"
    GH_REPO_DEST: "github.com/${ORG}/${REPO_DEST}.git"
    GH_REPO_CONSOLIDATE: "github.com/${ORG}/${REPO_CONSOLIDATE}.git"
    BUILD_USER: ${{ secrets.BUILD_USER }}
    BUILD_USER_PASSWD: ${{ secrets.BUILD_USER_PASSWD }}
    BUILD_USER_EMAIL:  ${{ secrets.BUILD_USER_EMAIL }}
    secure: SjDW/60KC9qs9IdFc2KBj0Yx2lIJm08DwMEH/jehphl5LRJFLKj7jIL4kK2tDecOdwoiLpPwQQyzqXbo+5xQOCgOkNQ2PhhSmgv7PfP7D91yjqYA/6xQFBFCp7RyRfK/RqIc
on:
    push:
        branches:
            - develop
name: Documentation
jobs:
    include:
        if:  ${{github.repository == 'devonfw/getting-started'}}
        runs-on: ubuntu-latest
        steps:
          - name: Clone necessary repositories
            run: |
                git clone https://${GH_REPO_DEST}
                git clone https://${GH_REPO_CONSOLIDATE}
            shell: bash
          - name: Clean up wiki repository, copy documentation there
            run: |
                cd ${REPO_DEST} && rm -rf * && cd ..
                yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
                cd ${REPO_DEST}
          - name: Remove .asciidoc file extension from relative links
            run: grep -lr "link:[a-zA-Z0-9_.-]*\.asciidoc\[" . | xargs -r sed -i "s/\(link:[a-zA-Z0-9_.-]*\)\.asciidoc\(\[\)/\1\2/g"
          - name: Terminate Travis CI build when no changes detected
            run: |
              if git diff-index --quiet HEAD && [ ! -n "$(git status -s)" ]; then 
              set +e 
              pkill -9 -P $$ &> /dev/null || true 
              exit 0
              else 
              git config user.email ${EMAIL}
              git config user.name ${USER}
              git status
              git add .
              git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
              git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_DEST}"
              git push origin-wiki master
          - name: Update snapshot in consolidated repository
            run: |
               cd ../${REPO_CONSOLIDATE}
               if [ ! -d ${REPO_DEST} ]; then git submodule add https://${GH_REPO_DEST}; fi;
               git submodule init
               git submodule update --recursive --remote
               cd ${REPO_DEST}
               git checkout master
               git pull
               cd ..
               git add .
               git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
               git remote add origin-wiki "https://${GITHUB_TOKEN}@${GH_REPO_CONSOLIDATE}"
               git push origin-wiki master
               fi
